In [7]:
import numpy as np
import pandas as pd

In [2]:
a=np.linspace(1,10,10)
b=np.linspace(11,20,10)

In [3]:
a,b

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]))

In [4]:
a+b

array([12., 14., 16., 18., 20., 22., 24., 26., 28., 30.])

In [6]:
np.add(a,b)

array([12., 14., 16., 18., 20., 22., 24., 26., 28., 30.])

In [10]:
df=pd.read_csv("data.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [12]:
df.index

RangeIndex(start=0, stop=169, step=1)

In [13]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')